//export const API = "http://localhost:4000"
//export const API = "https://gmailclone-backend.onrender.com"
// export const API = "https://gmailbackendclonecapstone.vercel.app"
//export const API = "https://gmailclone-backend-e7tj.onrender.com"
export const API= "https://gmailclone-task-backendnew1.onrender.com/"
